# Generated by Django 3.1 on 2021-01-30 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babysitter',
            name='age',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='communication',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='experience',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='babysitter',
            name='gender',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='age',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='communication',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gymmember',
            name='gender',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='age',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='city',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='communication',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='experience',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='gender',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
