# Generated by Django 3.1 on 2021-01-30 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_auto_20210130_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babysitter',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='gymmember',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='user',
            new_name='user_id',
        ),
    ]
