# Generated by Django 3.1 on 2021-01-31 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_auto_20210131_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babysitter',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='gymmember',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='trainer',
            old_name='user_id',
            new_name='user',
        ),
    ]
